### ISSUE TITLE
Notion is not allowing authentication

### ISSUE THREAD

**Issue by masonnness** [mkalvas/spotify#1]
Has anyone successfully embedded the spotify controls into notion? After embed, clicking "login to spotify" leads to a plain white page.

**Comment by mkalvas** [comment]
Hey @masonnness, thanks for your interest in this! There are a few things I wanted to let you know regarding this project.

First, this is super, super experimental. I never really "finished" it. There are some things like adding the theming endpoints, getting logged out after an hour of listening, using a different (slightly more appropriate and powerful) Spotify API for playback, and seeing if there was a way to get this working "properly" with authentication (see point 2) that I never got around to.

Second, unfortunately, Spotify doesn't allow iframes to go through their auth flow. This is a fairly normal security practice to minimize attack surface area for things like clickjacking. This means that you have to use this slightly convoluted flow to get it working:
  1. Open the actual app that's deployed at http://spotify.mkalvas.vercel.app (or your forked, deployed version)
  2. Log in there in one tab
  3. Go back to your notion tab with the same domain embedded for the playback controls to work.

It uses `localStorage` to transfer your auth token between browser tabs so that it can then be set while making requests to the Spotify API. This also means that the login is limited to the browser you're using — the notion desktop and mobile apps won't work at all with this project in its current state.

All of that said, I did have fun writing this and would be open to working on updating it if I can find some time. Particularly if there's a decent way to get more direct authentication working. I'm certainly open to pull requests and/or feedback if you feel like you want to help.

**Comment by masonnness** [comment]
@mkalvas Ahhh got it, well, you definitely have a great project so far. I was exclusively trying to get it to work on the notion desktop app, but the localstorage OAuth transfer for notion on the browser makes sense, just wouldn't quite work for what I was trying to do with a notion dashboard. 
I, unfortunately, am not aware of any other way to authenticate more directly, but thanks so much for sharing and for the quick response!

**Comment by mkalvas** [comment]
No problem. Thanks for bringing it up. I'll update back here if I end up making any progress on the "roadmap".
